# dev
spring:
  config:
    activate:
      on-profile: dev

  # datasource
  datasource:
    url: jdbc:mariadb://${rds_host}:3306/moongi_dev
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${rds_username}
    password: ${rds_password}

  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:

