name: Our Workflow
on:
  push:
    branches:
      - 'main'
  
jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:

    # build
      - name: Checkout Source
        uses: actions/checkout@v4
        
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
          # cache-dependency-path: |
          #   ./*.gradle*
          #   ./**/gradle-wrapper.properties

      - name: Grant Execute Permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build Project
        run: ./gradlew bootJar

      - name: Get Github Actions IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Add Github Actions IP to Security group
        run: aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          # TARGET: ${{ secrets.EC2_TARGET_DIR }}
          SOURCE: "./build/libs/moongi-dev-back-0.0.1-SNAPSHOT.jar"
          SCRIPT_BEFORE: |
            echo "SCRIPT_BEFORE start"
            EXISTING_PID=$(sudo lsof -t -i :${PORT_NUMBER} -sTCP:LISTEN)
            if [ -n "$EXISTING_PID" ]; then
              echo "Existing Java process found on port $PORT_NUMBER."
              sudo kill -9 $EXISTING_PID
            else
              echo "No existing Java process found on port $PORT_NUMBER."
            fi
          SCRIPT_AFTER:  |
            echo "SCRIPT_AFTER start"
            sudo su
            nohup /opt/jdk-17/bin/java -jar moongi-dev-back-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev &

      - name: Remove Github Actions IP From Security Group
        run: aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
